name: HIFITI-Auto-Checkin

on:
  workflow_dispatch:
  schedule:
    # UTC+8 ??:??
    - cron: "00 15 * * *"

jobs:
  checkin:
    name: Checkin
    runs-on: ubuntu-latest
    environment: HIFITI
    env:
      COOKIE: ${{ secrets.COOKIE }}

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js latest.
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Checkin
        shell: bash
        run: |
          node main.js
